[toolchain]
anchor_version="0.30.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
contract = "5nroogNoBjowEcCqDyPquSAxxp5fPVQ369GRmZghG8xF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "http://127.0.0.1:8899"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
